@startuml domain
package 企業集約 {
    object 企業 {
        法人名
        代表者名
        電話番号
        郵便場号
        住所
    }
    object ユーザー {
        氏名
        メールアドレス
        パスワード
    }
}

ユーザー "n" -right-* "1" 企業

package 取引先集約 {
    object 取引先 {
        法人名
        代表者名
        電話番号
        郵便場号
        住所
    }
    object 銀行 {
        銀行名
        支店名
        口座番号
        口座名
    }
}

package 請求書集約 {
    object 請求書 {
        発行日
        支払い金額
        手数料
        手数料率    
        消費税
        消費税率
        請求金額
        支払期日
        ステータス
    }
}

企業 "1..n" -down-> 取引先
取引先 -left-* 銀行

企業 "1..n" -left->  請求書
取引先 "1..n" -right-> 請求書

note right of 請求書 {
    * ステータスは「未処理」「処理中」「支払い済み」「エラー」
    　の4種類で未処理から始まる
    * 請求金額は支払い金額に手数料率と消費税を加えた金額とする
}

@enduml
